Mnpl 14
Platypuses/monopoly-backend pull request #7
Opened 2021-05-12 10:28 UTC by Jackie-Dou

2021-05-12 11:10 UTC, MerakseS requested changes

2021-05-12 11:10 UTC, MerakseS commented on src/main/services/LobbyService.ts
> +}
Лучше, наверное, назвать функцию isLobbyPartisipant() и возвращать true, если пользователь является участником лобби, и false - если нет

2021-05-12 11:10 UTC, MerakseS commented on src/main/services/LobbyService.ts
> +}
аналогично предыдущему

2021-05-12 12:09 UTC, Jackie-Dou commented on src/main/services/LobbyService.ts
> +}
Только вчера о подобном говорили со Святославом + придерживалась того что, что и в UserService - выброс исключений с текстом ошибки

2021-05-12 12:27 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +}
можно сделать функцию isLobbyParticipant() и использовать её в check

2021-05-12 12:27 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +}
ну и тут тоже, если нужна будет "is" функция, то лучше вынести

2021-05-12 12:43 UTC, Casper133 requested changes

2021-05-12 12:43 UTC, Casper133 commented on .run/Start.run.xml
> +    <package-manager value="D:\nodejs\node_modules\yarn" />
хардкод пути, который будет работать только у тебя, это ВебШторм так поставил?

2021-05-12 12:43 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +  const lobbyCreator = lobbyParticipants.find((element) => element.isCreator);
можно оптимизировать, достав сразу из БД создателя лобби:
```ts
const lobbyCreator = await getRepository(LobbyParticipant).findOne({
  lobby: { id: lobbyId },
  isCreator: true,
});
```

2021-05-12 12:43 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +    let lobby: Lobby = new Lobby();
не нужно явно писать тип ": Lobby", т.к. он автоматически определяется компилятором исходя из выражения после равно

2021-05-12 12:43 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +    let lobbyCreator: LobbyParticipant = new LobbyParticipant();
аналогично, не нужно явно указывать тип

2021-05-12 12:43 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +    }
Копипаст из UserService. Лучше там сделать метод, который вернет юзера (и бросит ошибку внутри)

2021-05-12 12:43 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +    }
скорее всего будет копипаститься, лучше сразу вынести в отдельный метод/функцию

2021-05-12 12:46 UTC, Jackie-Dou commented on .run/Start.run.xml
> +    <package-manager value="D:\nodejs\node_modules\yarn" />
Ага. Устанавливала внешним установщиком, не через npm, мб это сыграло

2021-05-12 12:46 UTC, Jackie-Dou commented on src/main/services/LobbyService.ts
> +}
Ок

2021-05-12 13:20 UTC, Casper133 commented on .run/Start.run.xml
> +    <package-manager value="D:\nodejs\node_modules\yarn" />
проверь конфигурацию запуска, наверное в package manager нужно project поставить

![image](https://user-images.githubusercontent.com/41972408/117981684-efa6e000-b33d-11eb-92ac-e2812ac30fde.png)

2021-05-12 13:22 UTC, Jackie-Dou commented on .run/Start.run.xml
> +    <package-manager value="D:\nodejs\node_modules\yarn" />
Проверила уже, она ломается - какая-то ошибка с наличием файла.
Сейчас нет времени разобраться, закончу с копипастом и только через пару часов смогу посмотреть это

2021-05-14 12:54 UTC, Casper133 requested changes

2021-05-14 12:54 UTC, Casper133 commented on .run/Start.run.xml
> +    <package-manager value="D:\nodejs\node_modules\yarn" />
всё ещё это есть в коде

2021-05-14 12:54 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +// import User from '../models/entities/User';
комментарий импорта, зачем?

2021-05-14 12:54 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +async function checkThatUserNotLobbyParticipant(userId: number) {
лучше ещё добавить is: checkThatUserIsNotLobbyParticipant

2021-05-14 12:54 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +}
тут уже лучше не check назвать, а getLobbyById (потому что есть возвращаемое значение)

2021-05-14 12:54 UTC, Casper133 commented on src/main/services/UserService.ts
> +  },
тут как с лобби, лучше назвать getUserById. Также в UserService в методе getUser() есть такой код, лучше вместо него сделать вызов метода getUserById

2021-05-15 08:02 UTC, MerakseS approved these changes, later dismissed
У меня только парочка доёбов до названий функций, но на них можно забить.

2021-05-15 08:02 UTC, MerakseS commented on .run/Start.run.xml
> +    <package-manager value="D:\nodejs\node_modules\yarn" />
@Casper133 , Этот файл, наверное, нужно в gitignore кинуть, потому что у меня конфигурация ярна сбивается

2021-05-15 08:02 UTC, MerakseS commented on src/main/services/LobbyService.ts
> +async function getLobbyExistsById(lobbyId: number): Promise<Lobby> {
Просто getLobbyById

2021-05-15 08:02 UTC, MerakseS commented on src/main/services/UserService.ts
> +  async getUserExistsById(userId: number): Promise<User> {
Можно просто getUserById

2021-05-15 10:53 UTC, Casper133 approved these changes

2021-05-15 10:55 UTC, merged