MNPL-15 | Getting info about lobby
Platypuses/monopoly-backend pull request #8
Opened 2021-05-12 14:48 UTC by MerakseS

2021-05-14 12:56 UTC, Casper133 commented
Вроде выглядит норм, ещё пересмотрю, когда изменения Кати попадут в девелоп, т.к. отчасти на их основе твой пулл реквест

2021-05-15 12:28 UTC, Casper133 requested changes

2021-05-15 12:28 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +async function checkThatUserParticipatesInLobby(user: User, lobby: Lobby) {
Ниже есть функции, которые делают то же самое

2021-05-15 12:28 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +      throw new ClientError(USER_DOES_NOT_EXIST);
Функция для этой проверки есть в UserService

2021-05-15 12:28 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +    const lobby = await getRepository(Lobby).findOne(lobbyId);
Есть функция getLobbyByIdIfExists

2021-05-15 12:28 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +      lobbyParticipants: lobby.lobbyParticipants.map((participant) => ({
Этот .map лучше сделать вне ретурна

2021-05-15 12:28 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +      lobbyMessages: lobby.lobbyMessages.map((message) => ({
Аналогично как с верхним мапом, лучше вынести вне ретурна

2021-05-15 12:38 UTC, MerakseS commented on src/main/services/LobbyService.ts
> +async function checkThatUserParticipatesInLobby(user: User, lobby: Lobby) {
Эти функции просто проверяют, состоит ли пользователь в каком-то лобби. А моя функция проверяет, является ли он участником конкретного лобби

2021-05-15 12:43 UTC, Casper133 commented on src/main/services/LobbyService.ts
> +async function checkThatUserParticipatesInLobby(user: User, lobby: Lobby) {
А, сорри

2021-05-15 12:55 UTC, Casper133 approved these changes

2021-05-15 12:56 UTC, merged